### ISSUE TITLE
implementing a data demo function

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/scidb.dplyr#8]
This is a general R development question.  How do I use a function like "cache_computation" in an R script if I was implementing a function such as nycflights13_sqlite? "cache_computation" is a internal function to dbplyr that doesn't seem to be exposed to the user. (https://github.com/tidyverse/dbplyr/blob/master/R/cache.r)

Is there is easy way to do this?

```
#' @export
#' @rdname nycflights13
#' @param path location of sqlite database file
nycflights13_sqlite <- function(path = NULL) {
  cache_computation("nycflights_sqlite", {
    path <- db_location(path, "nycflights13.sqlite")
    message("Caching nycflights db at ", path)
    src <- src_sqlite(path, create = TRUE)
    copy_nycflights13(src)
  })
}
```

**Comment by apoliakov** [comment]
dbplyr:::cache_computation?

**Comment by jrivers96** [comment]
dbplyr is not exported and available to the user.

**Comment by bwlewis** [comment]
If you want to use a function from a package, even a non-exported
function with :::, then you of course need that package installed
(dbplyr).

So install the package, then dbplyr:::cache_computation

**Comment by jrivers96** [comment]
Thanks
